version: '{build}'
os: Visual Studio 2017
branches:
  only:
  - master
environment:
  BUILDING_ON_PLATFORM: win
  BuildEnvironment: appveyor
skip_commits:
  files:
    - LICENSE
build_script:
- ps: ./build.ps1
test: off